version: '3.4'

services:
  kh.webapi:
    image: ${DOCKER_REGISTRY-}khwebapi
    build:
      context: .
      dockerfile: KH.WebApi/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssw0rd1
    volumes:
      - sqlserverdata:/var/opt/mssql

  angular-app:
    build:
      context: ./KH.WebClient
      dockerfile: Dockerfile
    depends_on:
      - kh.webapi

volumes:
  sqlserverdata:
