version: '3.4'

services:
  elasticsearch:
    environment:
      - xpack.monitoring.templates.enabled=true  # Enables monitoring templates
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # You can adjust the memory settings as needed
      - discovery.type=single-node

  kibana:
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
