version: '3.4'

services:
  elasticsearch:
    environment:
      - xpack.monitoring.enabled=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  kibana:
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
