/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { EmailTrackerResponseApiResponse } from '../model/emailTrackerResponseApiResponse';
// @ts-ignore
import { EmailTrackerResponsePagedListApiResponse } from '../model/emailTrackerResponsePagedListApiResponse';
// @ts-ignore
import { MailRequest } from '../model/mailRequest';
// @ts-ignore
import { MailTypeEnum } from '../model/mailTypeEnum';
// @ts-ignore
import { StringApiResponse } from '../model/stringApiResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface ApiV1EmailIdGetRequestParams {
    id: number;
}

export interface ApiV1EmailListPostRequestParams {
    mailRequest?: MailRequest;
}

export interface ApiV1EmailSendPostRequestParams {
    toEmail?: Array<string>;
    toCCEmail?: Array<string>;
    subject?: string;
    body?: string;
    attachments?: Array<Blob>;
    mailType?: MailTypeEnum;
    modelId?: number;
    model?: string;
    prefaredLanguageKey?: string;
    isSent?: boolean;
    pageIndex?: number;
    pageSize?: number;
    sort?: string;
    search?: string;
}


@Injectable({
  providedIn: 'root'
})
export class EmailService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EmailIdGet(requestParameters: ApiV1EmailIdGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<EmailTrackerResponseApiResponse>;
    public apiV1EmailIdGet(requestParameters: ApiV1EmailIdGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EmailTrackerResponseApiResponse>>;
    public apiV1EmailIdGet(requestParameters: ApiV1EmailIdGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EmailTrackerResponseApiResponse>>;
    public apiV1EmailIdGet(requestParameters: ApiV1EmailIdGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1EmailIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Basic) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Basic', 'Authorization', localVarHeaders, 'Basic ');

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/Email/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EmailTrackerResponseApiResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EmailListPost(requestParameters?: ApiV1EmailListPostRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<EmailTrackerResponsePagedListApiResponse>;
    public apiV1EmailListPost(requestParameters?: ApiV1EmailListPostRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EmailTrackerResponsePagedListApiResponse>>;
    public apiV1EmailListPost(requestParameters?: ApiV1EmailListPostRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EmailTrackerResponsePagedListApiResponse>>;
    public apiV1EmailListPost(requestParameters?: ApiV1EmailListPostRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const mailRequest = requestParameters?.mailRequest;

        let localVarHeaders = this.defaultHeaders;

        // authentication (Basic) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Basic', 'Authorization', localVarHeaders, 'Basic ');

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/Email/list`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EmailTrackerResponsePagedListApiResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: mailRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EmailSendPost(requestParameters?: ApiV1EmailSendPostRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<StringApiResponse>;
    public apiV1EmailSendPost(requestParameters?: ApiV1EmailSendPostRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<StringApiResponse>>;
    public apiV1EmailSendPost(requestParameters?: ApiV1EmailSendPostRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<StringApiResponse>>;
    public apiV1EmailSendPost(requestParameters?: ApiV1EmailSendPostRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const toEmail = requestParameters?.toEmail;
        const toCCEmail = requestParameters?.toCCEmail;
        const subject = requestParameters?.subject;
        const body = requestParameters?.body;
        const attachments = requestParameters?.attachments;
        const mailType = requestParameters?.mailType;
        const modelId = requestParameters?.modelId;
        const model = requestParameters?.model;
        const prefaredLanguageKey = requestParameters?.prefaredLanguageKey;
        const isSent = requestParameters?.isSent;
        const pageIndex = requestParameters?.pageIndex;
        const pageSize = requestParameters?.pageSize;
        const sort = requestParameters?.sort;
        const search = requestParameters?.search;

        let localVarHeaders = this.defaultHeaders;

        // authentication (Basic) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Basic', 'Authorization', localVarHeaders, 'Basic ');

        // authentication (Bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (toEmail) {
            toEmail.forEach((element) => {
                localVarFormParams = localVarFormParams.append('ToEmail', <any>element) as any || localVarFormParams;
            })
        }
        if (toCCEmail) {
            toCCEmail.forEach((element) => {
                localVarFormParams = localVarFormParams.append('ToCCEmail', <any>element) as any || localVarFormParams;
            })
        }
        if (subject !== undefined) {
            localVarFormParams = localVarFormParams.append('Subject', <any>subject) as any || localVarFormParams;
        }
        if (body !== undefined) {
            localVarFormParams = localVarFormParams.append('Body', <any>body) as any || localVarFormParams;
        }
        if (attachments) {
            attachments.forEach((element) => {
                localVarFormParams = localVarFormParams.append('Attachments', <any>element) as any || localVarFormParams;
            })
        }
        if (mailType !== undefined) {
            localVarFormParams = localVarFormParams.append('MailType', <any>mailType) as any || localVarFormParams;
        }
        if (modelId !== undefined) {
            localVarFormParams = localVarFormParams.append('ModelId', <any>modelId) as any || localVarFormParams;
        }
        if (model !== undefined) {
            localVarFormParams = localVarFormParams.append('Model', <any>model) as any || localVarFormParams;
        }
        if (prefaredLanguageKey !== undefined) {
            localVarFormParams = localVarFormParams.append('PrefaredLanguageKey', <any>prefaredLanguageKey) as any || localVarFormParams;
        }
        if (isSent !== undefined) {
            localVarFormParams = localVarFormParams.append('IsSent', <any>isSent) as any || localVarFormParams;
        }
        if (pageIndex !== undefined) {
            localVarFormParams = localVarFormParams.append('PageIndex', <any>pageIndex) as any || localVarFormParams;
        }
        if (pageSize !== undefined) {
            localVarFormParams = localVarFormParams.append('PageSize', <any>pageSize) as any || localVarFormParams;
        }
        if (sort !== undefined) {
            localVarFormParams = localVarFormParams.append('Sort', <any>sort) as any || localVarFormParams;
        }
        if (search !== undefined) {
            localVarFormParams = localVarFormParams.append('Search', <any>search) as any || localVarFormParams;
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/Email/Send`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<StringApiResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
