/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006494",
        "background": "#f8f9fe",
        "outline": "#707880",
        "primary-container": "#006494",
        "inverse-primary": "#8ecdff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-background": "#191c1f",
        "on-tertiary-fixed-variant": "#004884",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#95d4b3",
        "primary": "#004b71",
        "on-primary-container": "#b6ddff",
        "primary-fixed": "#cbe6ff",
        "surface-variant": "#e0e2e7",
        "on-secondary-fixed-variant": "#0e5138",
        "tertiary": "#004784",
        "inverse-on-surface": "#eff1f5",
        "surface-container-highest": "#e0e2e7",
        "tertiary-fixed": "#d4e3ff",
        "on-primary-fixed": "#001e30",
        "secondary-fixed": "#b1f0ce",
        "surface-bright": "#f8f9fe",
        "on-secondary-container": "#316e52",
        "on-primary-fixed-variant": "#004b71",
        "on-tertiary": "#ffffff",
        "secondary": "#2c694e",
        "outline-variant": "#c0c7d0",
        "surface-container-low": "#f2f4f8",
        "secondary-container": "#aeeecb",
        "surface-container": "#eceef2",
        "tertiary-container": "#005fac",
        "on-tertiary-fixed": "#001c39",
        "surface-container-high": "#e6e8ed",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dade",
        "on-surface-variant": "#40484f",
        "on-tertiary-container": "#c3daff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1f",
        "on-secondary-fixed": "#002114",
        "surface": "#f8f9fe",
        "tertiary-fixed-dim": "#a4c9ff",
        "primary-fixed-dim": "#8ecdff",
        "inverse-surface": "#2d3134"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
    require('tailwindcss-primeui')
  ],
}
