/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "var(--md-surface-tint)",
        "background": "var(--md-background)",
        "outline": "var(--md-outline)",
        "primary-container": "var(--md-primary-container)",
        "inverse-primary": "var(--md-inverse-primary)",
        "error": "var(--md-error)",
        "on-error": "var(--md-on-error)",
        "on-background": "var(--md-on-background)",
        "on-tertiary-fixed-variant": "var(--md-on-tertiary-fixed-variant)",
        "on-primary": "var(--md-on-primary)",
        "secondary-fixed-dim": "var(--md-secondary-fixed-dim)",
        "primary": "var(--md-primary)",
        "on-primary-container": "var(--md-on-primary-container)",
        "primary-fixed": "var(--md-primary-fixed)",
        "surface-variant": "var(--md-surface-variant)",
        "on-secondary-fixed-variant": "var(--md-on-secondary-fixed-variant)",
        "tertiary": "var(--md-tertiary)",
        "inverse-on-surface": "var(--md-inverse-on-surface)",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "tertiary-fixed": "var(--md-tertiary-fixed)",
        "on-primary-fixed": "var(--md-on-primary-fixed)",
        "secondary-fixed": "var(--md-secondary-fixed)",
        "surface-bright": "var(--md-surface-bright)",
        "on-secondary-container": "var(--md-on-secondary-container)",
        "on-primary-fixed-variant": "var(--md-on-primary-fixed-variant)",
        "on-tertiary": "var(--md-on-tertiary)",
        "secondary": "var(--md-secondary)",
        "outline-variant": "var(--md-outline-variant)",
        "surface-container-low": "var(--md-surface-container-low)",
        "secondary-container": "var(--md-secondary-container)",
        "surface-container": "var(--md-surface-container)",
        "tertiary-container": "var(--md-tertiary-container)",
        "on-tertiary-fixed": "var(--md-on-tertiary-fixed)",
        "surface-container-high": "var(--md-surface-container-high)",
        "on-secondary": "var(--md-on-secondary)",
        "error-container": "var(--md-error-container)",
        "on-error-container": "var(--md-on-error-container)",
        "surface-dim": "var(--md-surface-dim)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        "on-tertiary-container": "var(--md-on-tertiary-container)",
        "surface-container-lowest": "var(--md-surface-container-lowest)",
        "on-surface": "var(--md-on-surface)",
        "on-secondary-fixed": "var(--md-on-secondary-fixed)",
        "surface": "var(--md-surface)",
        "tertiary-fixed-dim": "var(--md-tertiary-fixed-dim)",
        "primary-fixed-dim": "var(--md-primary-fixed-dim)",
        "inverse-surface": "var(--md-inverse-surface)"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
    require('tailwindcss-primeui')
  ],
}
