export * from './audits.service';
import { AuditsService } from './audits.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './chat.service';
import { ChatService } from './chat.service';
export * from './departments.service';
import { DepartmentsService } from './departments.service';
export * from './email.service';
import { EmailService } from './email.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './jobTest.service';
import { JobTestService } from './jobTest.service';
export * from './locking.service';
import { LockingService } from './locking.service';
export * from './media.service';
import { MediaService } from './media.service';
export * from './pdf.service';
import { PdfService } from './pdf.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './sms.service';
import { SmsService } from './sms.service';
export * from './smsTemplates.service';
import { SmsTemplatesService } from './smsTemplates.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AuditsService, AuthenticationService, ChatService, DepartmentsService, EmailService, GroupsService, JobTestService, LockingService, MediaService, PdfService, PermissionsService, RolesService, SmsService, SmsTemplatesService, UsersService];
