/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSmsTrackerRequest { 
    id?: number | null;
    mobileNumber?: string | null;
    message?: string | null;
    isSent?: boolean | null;
    isPending?: boolean;
    failureReasons?: string | null;
    status?: string | null;
    model?: string | null;
    modelId?: number;
}

