/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleResponse } from './userRoleResponse';


export interface AuthenticationResponse { 
    AccessToken?: string | null;
    RefreshToken?: string | null;
    NeedVerification?: boolean | null;
    UserRoles?: Array<UserRoleResponse> | null;
}

