/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatUser } from './chatUser';


export interface ChatMessages { 
    user?: ChatUser;
    message?: string | null;
    time?: string;
    isCurrentUser?: boolean;
}

