/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatUser { 
    Id?: string | null;
    Name?: string | null;
    Group?: string | null;
    LastOn?: string;
}

