/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSmsTrackerRequest { 
    Id?: number | null;
    MobileNumber?: string | null;
    Message?: string | null;
    IsSent?: boolean | null;
    IsPending?: boolean;
    FailureReasons?: string | null;
    Status?: string | null;
    Model?: string | null;
    ModelId?: number;
}

