/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSmsTemplateRequest { 
    Id?: number | null;
    SmsType?: string | null;
    TextEn?: string | null;
    TextAr?: string | null;
}

