/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupListResponse { 
    Id?: number | null;
    NameAr?: string | null;
    NameEn?: string | null;
    Description?: string | null;
    IsDeleted?: boolean;
}

