/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupListResponse } from './groupListResponse';


export interface GroupListResponsePagedList { 
    CurrentPage?: number;
    TotalPages?: number;
    PageSize?: number;
    TotalCount?: number;
    Items?: Array<GroupListResponse> | null;
}

