/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailTypeEnum } from './mailTypeEnum';


export interface MailRequest { 
    pageIndex?: number;
    pageSize?: number;
    sort?: string | null;
    search?: string | null;
    toEmail?: Array<string> | null;
    toCCEmail?: Array<string> | null;
    subject?: string | null;
    body?: string | null;
    attachments?: Array<Blob> | null;
    mailType?: MailTypeEnum;
    modelId?: number;
    model?: string | null;
    prefaredLanguageKey?: string | null;
    isSent?: boolean;
}
export namespace MailRequest {
}


