/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaResponse } from './mediaResponse';


export interface MediaResponseApiResponse { 
    data?: MediaResponse;
    statusCode?: number;
    errors?: Array<string> | null;
    errorMessage?: string | null;
    errorCode?: string | null;
    errorMessageAr?: string | null;
}

