/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaRequest { 
    pageIndex?: number;
    pageSize?: number;
    sort?: string | null;
    search?: string | null;
    fileName?: string | null;
    orignalName?: string | null;
    path?: string | null;
    model?: string | null;
    modelId?: number | null;
}

