/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaResponse { 
    Id?: number | null;
    CreatedDate?: string;
    CreatedById?: number | null;
    UpdatedDate?: string | null;
    UpdatedById?: number | null;
    IsDeleted?: boolean;
    DeletedDate?: string | null;
    DeletedById?: number | null;
    FileContentResult?: Blob | null;
    IsValidToDownload?: boolean;
    Message?: string | null;
    FileName?: string | null;
    OrignalName?: string | null;
    FileExtention?: string | null;
    ContentType?: string | null;
    Model?: string | null;
    ModelId?: number | null;
    FilePath?: string | null;
}

