/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionResponse } from './permissionResponse';


export interface PermissionResponseListApiResponse { 
    Data?: Array<PermissionResponse> | null;
    StatusCode?: number;
    Errors?: Array<string> | null;
    ErrorMessage?: string | null;
    ErrorCode?: string | null;
    ErrorMessageAr?: string | null;
}

