/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmsTrackerFilterRequest { 
    pageIndex?: number;
    pageSize?: number;
    sort?: string | null;
    search?: string | null;
    id?: number | null;
    status?: string | null;
    isSent?: boolean;
    isDeleted?: boolean;
    modelId?: number | null;
    model?: string | null;
}

