/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmsTrackerFilterRequest { 
    PageIndex?: number;
    PageSize?: number;
    Sort?: string | null;
    Search?: string | null;
    Id?: number | null;
    Status?: string | null;
    IsSent?: boolean;
    IsDeleted?: boolean;
    ModelId?: number | null;
    Model?: string | null;
}

