/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserListResponse } from './userListResponse';


export interface UserListResponsePagedList { 
    CurrentPage?: number;
    TotalPages?: number;
    PageSize?: number;
    TotalCount?: number;
    Items?: Array<UserListResponse> | null;
}

