/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleResponse } from './userRoleResponse';


export interface UserListResponse { 
    id?: number | null;
    createdDate?: string;
    createdById?: number | null;
    updatedDate?: string | null;
    updatedById?: number | null;
    isDeleted?: boolean;
    deletedDate?: string | null;
    deletedById?: number | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    username?: string | null;
    birthDate?: string | null;
    mobileNumber?: string | null;
    departmentNames?: Array<string> | null;
    userRoles?: Array<UserRoleResponse> | null;
}

