/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleResponse } from './userRoleResponse';
import { UserGroupResponse } from './userGroupResponse';
import { UserDepartmentResponse } from './userDepartmentResponse';


export interface UserDetailsResponse { 
    Id?: number | null;
    CreatedDate?: string;
    CreatedById?: number | null;
    UpdatedDate?: string | null;
    UpdatedById?: number | null;
    IsDeleted?: boolean;
    DeletedDate?: string | null;
    DeletedById?: number | null;
    SensitiveData?: string | null;
    FirstName?: string | null;
    MiddleName?: string | null;
    LastName?: string | null;
    Email?: string | null;
    Username?: string | null;
    Token?: string | null;
    BirthDate?: string | null;
    MobileNumber?: string | null;
    GroupId?: number | null;
    DepartmentId?: number | null;
    RoleIds?: Array<number> | null;
    PrefaredLanguageKey?: string | null;
    LastAssignDateAsSupervisor?: string | null;
    LastAssignDateAsCaseOwner?: string | null;
    LastAssignDateAsAssignTo?: string | null;
    UserRoles?: Array<UserRoleResponse> | null;
    UserGroups?: Array<UserGroupResponse> | null;
    UserDepartments?: Array<UserDepartmentResponse> | null;
    readonly FullName?: string | null;
}

