/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolesPermissionResponse } from './rolesPermissionResponse';
import { RoleResponse } from './roleResponse';


export interface UserRoleResponse { 
    UserId?: number;
    RoleId?: number;
    Role?: RoleResponse;
    RoleFunctions?: Array<RolesPermissionResponse> | null;
}

