/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditResponse { 
    id?: number;
    userId?: string | null;
    type?: string | null;
    tableName?: string | null;
    dateTime?: string | null;
    oldValues?: string | null;
    newValues?: string | null;
    affectedColumns?: string | null;
    primaryKey?: string | null;
}

