/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditResponse } from './auditResponse';


export interface AuditResponseListApiResponse { 
    data?: Array<AuditResponse> | null;
    statusCode?: number;
    errors?: Array<string> | null;
    errorMessage?: string | null;
    errorCode?: string | null;
    errorMessageAr?: string | null;
}

