/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePermissionRequest { 
    id?: number | null;
    createdDate?: string;
    createdById?: number | null;
    updatedDate?: string | null;
    updatedById?: number | null;
    isDeleted?: boolean;
    deletedDate?: string | null;
    deletedById?: number | null;
    nameAr?: string | null;
    nameEn?: string | null;
    description?: string | null;
    isUpdateMode?: boolean;
    sortKey?: number;
    parentId?: number | null;
}

