/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupListResponse { 
    id?: number | null;
    nameAr?: string | null;
    nameEn?: string | null;
    description?: string | null;
    isDeleted?: boolean;
}

