/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionResponse { 
    id?: number;
    key?: string | null;
    nameEn?: string | null;
    nameAr?: string | null;
    disabled?: boolean;
    checked?: boolean;
    childrens?: Array<PermissionResponse> | null;
    sortKey?: number;
    parentId?: number | null;
}

