/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleListResponse } from './roleListResponse';


export interface RoleListResponsePagedList { 
    currentPage?: number;
    totalPages?: number;
    pageSize?: number;
    totalCount?: number;
    items?: Array<RoleListResponse> | null;
}

