/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleFilterRequest { 
    pageIndex?: number;
    pageSize?: number;
    sort?: string | null;
    search?: string | null;
    id?: number | null;
    nameEn?: string | null;
    nameAr?: string | null;
    description?: string | null;
    model?: string | null;
    modelId?: number | null;
    isDeleted?: boolean | null;
    isSent?: boolean;
    requestFromCustomerPortal?: boolean | null;
    reportToRoleId?: number | null;
}

