/**
 * Clean Architecture Web API V1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserFilterRequest { 
    pageIndex?: number;
    pageSize?: number;
    sort?: string | null;
    search?: string | null;
    id?: number | null;
    email?: string | null;
    userName?: string | null;
    language?: string | null;
    groupId?: number | null;
    departmentId?: number | null;
    roleId?: number | null;
    isDeleted?: boolean | null;
}

